version: '3.8'

services:
  api:
    build:
      context: ./backend/API
      dockerfile: Dockerfile
    ports:
      - "${API_HTTP_PORT:-5054}:80"
      - "${API_HTTPS_PORT:-7294}:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNET_ENVIRONMENT:-Development}
      - API_URLS=http://+:80;https://+:443
      - AllowedOrigins__0=http://localhost:${FRONTEND_PORT:-3000}
      - AllowedOrigins__1=http://frontend:${FRONTEND_PORT:-3000}
    networks:
      - skill-management-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:${API_HTTP_PORT:-5054}/api
    depends_on:
      - api
    networks:
      - skill-management-network

networks:
  skill-management-network:
    driver: bridge
