name: Azure Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'deploy/**'
      - '.github/workflows/azure-deploy.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Azure Infrastructure
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./deploy/main.bicep
          parameters: ./deploy/parameters.${{ github.event.inputs.environment || 'dev' }}.json sqlAdminPassword=${{ secrets.SQL_ADMIN_PASSWORD }}
          failOnStdErr: false

  build-and-deploy-api:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Build and Publish API
        run: |
          cd backend/API
          dotnet restore
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./publish
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy API to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'skillmgmt-${{ github.event.inputs.environment || "dev" }}-api'
          package: './backend/API/publish'
          
  build-and-deploy-frontend:
    needs: build-and-deploy-api
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build
        env:
          REACT_APP_API_URL: 'https://skillmgmt-${{ github.event.inputs.environment || "dev" }}-api.azurewebsites.net/api'
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Frontend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'skillmgmt-${{ github.event.inputs.environment || "dev" }}-web'
          package: './frontend/build'
